Solution fp2
fey/study pull request #3
Opened 2021-08-14 16:49 UTC by fey

2021-10-22 14:12 UTC, NickelGit commented
> Здесь всё из задач arrays, fp, fp2 потому что поздно фиксанул пайплайн
> Плюс подключил github actions, аналогично тревису (можно глянуть пайплайн его, не смог сходу разобраться, что с ним)

Кажется пайплан все еще падает. Раздели пожалуйста пул-реквесты согласно заданиям. (по одному пул-реквесту на каждую задачу.) Если починить пайплайн не получится - попробуй создать ветки в которых будут только изменения необходимые для выполнения задачи (черрипикни в них нужные коммиты, или скопируй код если нет чистых коммитов в которых только необходимый код).

2021-10-22 20:03 UTC, fey commented
@NickelGit вместо тревиса подключил гитхаб экшенс и он не падает (тесты, линтеры на месте). Это не подойдет? Может тревис удалить из репы?

2021-10-22 21:01 UTC, fey commented
Fixed

2021-10-25 11:40 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +        end
my_each нужно реализовать через рекурсию

2021-10-25 11:40 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +        end
map и compact нужно реализовать через my_reduce

2021-10-25 11:40 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +      end
Тоже через рекурсию. Циклы - это не про функциональное программирование.

2021-11-17 20:27 UTC, fey commented on test/exercise/fp2/solution.rb
> +        end
fixed

2021-11-17 20:34 UTC, fey commented on test/exercise/fp2/solution.rb
> +        end
fixed

2021-11-17 20:34 UTC, fey commented on test/exercise/fp2/solution.rb
> +      end
fixed

2021-11-18 15:01 UTC, moklidia requested changes

2021-11-18 15:01 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +          if block_given?
А разве в компакт можно передать блок?

2021-11-18 15:24 UTC, fey commented on test/exercise/fp2/solution.rb
> +          if block_given?
Действительно, нельзя. 
Fixed

2021-11-19 11:09 UTC, moklidia approved these changes

2021-11-19 11:39 UTC, merged